name: run main.py
on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script
        run: python main.py
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          timestamp=$(date -u)
          git add -A
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/baseball-git-scraper
          git diff-index --quiet HEAD || (git commit -a -m "Add more data ${timestamp}" --allow-empty)
      - name: push changes
        run: |
          git push
